/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package POEprojectFinal;
import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
        boolean checkUserName = false;

        while (!checkUserName) {
            String username = JOptionPane.showInputDialog("Create username:" + "\n" + "Username must be 5 characters long and contain an _");
            int userSize = username.length();

            boolean checkUserLength = userSize >= 5;
            //boolean checkUserSpecial = username.contains("_");
            
            boolean checkUserSpecial = false;
            
            for (char ch : username.toCharArray()) 
            {
            if ("_".contains(String.valueOf(ch))) {
            checkUserSpecial = true;
            break;
                    }
                }
            
            checkUserName = checkUserLength && checkUserSpecial;

            if (checkUserName) {
                String userMessage = "Username successfully captured";
                JOptionPane.showMessageDialog(null, userMessage);
            } else {
                String userMessageFail = "Username is not correctly formatted. Please ensure that your username contains an underscore and is no more than 5 characters in length.";
                JOptionPane.showMessageDialog(null, userMessageFail);
            }
        }

        boolean checkPasswordComplexity = false;

        while (!checkPasswordComplexity) 
        {
        
        String password = JOptionPane.showInputDialog("Create Password:" + "\n" + "Password must be 8 characters long, contain a capital, symbol and a number");
        int passwordSize = password.length();

        boolean checkPasswordLength = passwordSize >= 8;
    boolean checkPasswordSpecial = false;
    boolean checkPasswordCapital = false;
    boolean checkPasswordNumber = false;

    for (char ch : password.toCharArray()) {
        if ("!@#$%^&*<>?".contains(String.valueOf(ch))) {
            checkPasswordSpecial = true;
        } else if (Character.isUpperCase(ch)) {
            checkPasswordCapital = true;
        } else if (Character.isDigit(ch)) {
            checkPasswordNumber = true;
        }
    }

    checkPasswordComplexity = checkPasswordLength && checkPasswordSpecial && checkPasswordCapital && checkPasswordNumber;
        //boolean checkPasswordComplexity = checkPasswordLength && checkPasswordSpecial && checkPasswordCapital;

        if (checkPasswordComplexity) {
            String passwordMessage = "Password successfully captured";
            JOptionPane.showMessageDialog(null, passwordMessage);
        } else {
            String passwordMessageFail = "Password is not correctly formatted.";
            JOptionPane.showMessageDialog(null, passwordMessageFail);
        }
    }

    String DetailConfirm = "Your Log in details are:" + "\n" + checkUserName + "\n" + checkPasswordComplexity;
    JOptionPane.showMessageDialog(null, DetailConfirm);
}
}